# Generated by Django 4.1.2 on 2023-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='meeting_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
