# Generated by Django 4.1.2 on 2023-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_response_meeting_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
