# Generated by Django 4.1.2 on 2023-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_rename_jon_url_response_join_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='doctorack',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
