# Generated by Django 4.1.2 on 2023-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_patientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='payment_status',
            field=models.TextField(blank=True, default='NA', max_length=150, null=True),
        ),
    ]
