# Generated by Django 4.1.2 on 2023-02-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_review'),
        ('doctor', '0004_blockeduser_spamreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=200, null=True)),
                ('reqdate', models.DateField(null=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordata')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Latenight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=200, null=True)),
                ('reqdate', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('declined', 'Declined'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='Pending', max_length=30, null=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordata')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Emgergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=200, null=True)),
                ('reqdate', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('declined', 'Declined'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='Pending', max_length=30, null=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordata')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
