# Generated by Django 4.1.2 on 2023-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_userdata_active_day_userdata_active_time_end_and_more'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emgergency',
            name='patientid',
        ),
        migrations.RemoveField(
            model_name='emgergency',
            name='reqdate',
        ),
        migrations.AddField(
            model_name='emgergency',
            name='reqdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emgergency',
            name='doctorid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_data_req', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='emgergency',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_data_req', to='user.userprofile'),
        ),
    ]
