# Generated by Django 4.1.2 on 2023-03-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_emgergency_patientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emgergency',
            old_name='doctorid',
            new_name='doctor_profile',
        ),
        migrations.RenameField(
            model_name='emgergency',
            old_name='userid',
            new_name='user_profile',
        ),
    ]
