# Generated by Django 4.1.2 on 2023-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_doctorid_emgergency_doctor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emgergency',
            name='doctor_profile',
        ),
        migrations.RemoveField(
            model_name='emgergency',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='emgergency',
            name='doctorid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emgergency',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
