# Generated by Django 4.1.2 on 2023-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_emgergency_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emgergency',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=30, null=True),
        ),
    ]
