# Generated by Django 4.1.2 on 2023-03-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_patient_created_at'),
        ('request', '0006_alter_emgergency_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emgergency',
            name='doctorid',
        ),
        migrations.RemoveField(
            model_name='emgergency',
            name='userid',
        ),
        migrations.AddField(
            model_name='emgergency',
            name='doctor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_data_req', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='emgergency',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_data', to='user.patient'),
        ),
        migrations.AddField(
            model_name='emgergency',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data_req', to='user.userprofile'),
        ),
    ]
