# Generated by Django 4.1.2 on 2023-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=190, null=True)),
                ('dob', models.DateField(null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('monthly_income', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('NID', models.CharField(max_length=20, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=30, null=True)),
            ],
        ),
    ]
