# Generated by Django 4.1.2 on 2023-01-21 18:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('NID', models.CharField(max_length=20, unique=True)),
                ('userimage', models.ImageField(upload_to='user/images')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=30, null=True)),
                ('phonenumber', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
