# Generated by Django 4.1.2 on 2023-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('monthly_income', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('NID', models.CharField(max_length=20, null=True, unique=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
