# Generated by Django 4.1.2 on 2023-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdata_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
