# Generated by Django 4.1.2 on 2023-02-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
    ]
