# Generated by Django 4.1.2 on 2023-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
