# Generated by Django 4.1.2 on 2023-02-25 10:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userdata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
