# Generated by Django 4.1.2 on 2023-02-26 10:52

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', user.models.UserProfileManager()),
            ],
        ),
    ]
