# Generated by Django 4.1.2 on 2023-02-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userprofile_otp_userprofile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_created_at',
        ),
    ]
