# Generated by Django 4.1.2 on 2023-03-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_userdata_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='rating',
        ),
    ]
