# Generated by Django 4.1.2 on 2023-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
