# Generated by Django 4.1.2 on 2023-03-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_userdata_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='gender',
        ),
    ]
