# Generated by Django 4.1.2 on 2023-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='active_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='active_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='active_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
