# Generated by Django 4.1.2 on 2023-03-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_userdata_active_day_userdata_active_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
