# Generated by Django 4.1.2 on 2023-03-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_patient_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='userid',
            new_name='user_profile',
        ),
    ]
