# Generated by Django 4.1.2 on 2023-03-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_patient_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
