# Generated by Django 4.1.2 on 2023-03-28 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='meeting_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='subscribe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 28, 19, 0, 17, 127653, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
