# Generated by Django 4.1.2 on 2023-03-28 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_userdata_meeting_count_userdata_subscribe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 28, 22, 18, 10, 372077, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
