# Generated by Django 4.1.2 on 2023-03-28 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 28, 22, 58, 32, 723551, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
