# Generated by Django 4.1.2 on 2023-03-30 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 0, 21, 16, 249912, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
