# Generated by Django 4.1.2 on 2023-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('regnum', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('latenightstatus', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
