# Generated by Django 4.1.2 on 2023-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='NID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='chamberaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='degrees',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='doctoremail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='regtype',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('dental', 'Dental')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='working_hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
