# Generated by Django 4.1.2 on 2023-02-01 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctordata_nid_doctordata_chamberaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activedoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordata')),
            ],
        ),
    ]
