# Generated by Django 4.1.2 on 2023-02-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_activedoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockuserid', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spamreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('spamcount', models.IntegerField(null=True)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctordata')),
            ],
        ),
    ]
