# Generated by Django 4.1.2 on 2023-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_doctordata_activetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='activetime',
            field=models.IntegerField(default=0),
        ),
    ]
