# Generated by Django 4.1.2 on 2023-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctordata_activetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='activetime',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='active_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='active_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='active_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
