# Generated by Django 4.1.2 on 2023-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctordata_activetime_doctordata_active_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='newpassword',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='oldpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
