# Generated by Django 4.1.2 on 2023-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctordata_confirmpassword_doctordata_newpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
