# Generated by Django 4.1.2 on 2023-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctordata_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
