# Generated by Django 4.1.2 on 2023-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctordata_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='visits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
