# Generated by Django 4.1.2 on 2023-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_doctordata_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
