# Generated by Django 4.1.2 on 2023-03-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctordata_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
