# Generated by Django 4.1.2 on 2023-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_doctordata_ratingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
